<?php  /*** @file* This is     contactlistmodule     module.*/

function loadtable_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'loadtable/custom_css';
}

function loadtable_theme($existing, $type, $theme, $path) {
  return [
    'contacts_theme' => [
      'render element' => 'form',
    ],
    'edit_address' => [
      'render element' => 'form',
    ],
  ];
}

function loadtable_form(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['#prefix'] = '<div id=addMoreCallback">';
  $form['#suffix'] = '</div>';

  // adjust the form to use ajax submit
  $form['actions']['submit']['#ajax'] = array(
    'callback' => 'contact_ajax_contact_site_form_ajax_callback',
    'wrapper' => 'addMoreCallback',
  );
}
